import type { ExportOptions } from '@/types';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  PageBreak,
  Header,
  Footer,
  ImageRun,
} from 'docx';

/**
 * DocMint DOCX Generator
 * Generates Microsoft Word (.docx) documents using the docx library.
 * Compatible with Next.js App Router and ESM environments.
 */
export class DOCXGenerator {
  /**
   * Generate a DOCX file from HTML content
   */
  static async generate(
    htmlContent: string,
    options: Partial<ExportOptions> & { title?: string } = {}
  ): Promise<Buffer> {
    try {
      // Parse HTML content into docx elements
      const children = this.parseHtmlToDocxElements(htmlContent);

      // Create the document
      const doc = new Document({
        title: options.title || 'Document',
        creator: 'DocMint',
        description: 'Generated by DocMint',
        styles: {
          default: {
            document: {
              run: {
                size: 22, // 11pt
                font: 'Calibri',
              },
            },
          },
        },
        sections: [
          {
            properties: {
              page: {
                margin: {
                  top: 1440, // 1 inch in twips
                  right: 1440,
                  bottom: 1440,
                  left: 1440,
                },
              },
            },
            children,
          },
        ],
      });

      // Generate buffer
      const buffer = await Packer.toBuffer(doc);
      return Buffer.from(buffer);
    } catch (error) {
      console.error('DOCX generation error:', error);
      throw new Error('Failed to generate DOCX document');
    }
  }

  /**
   * Generate a preview (returns HTML representation)
   */
  static async generatePreview(htmlContent: string): Promise<string> {
    return htmlContent;
  }

  /**
   * Parse simple HTML content into docx paragraph elements
   */
  private static parseHtmlToDocxElements(html: string): (Paragraph | Table)[] {
    const elements: (Paragraph | Table)[] = [];

    // Extract text content from HTML tags
    const textContent = html
      .replace(/<br\s*\/?>/gi, '\n')
      .replace(/<\/p>/gi, '\n')
      .replace(/<\/h[1-6]>/gi, '\n')
      .replace(/<\/div>/gi, '\n')
      .replace(/<[^>]*>/g, '')
      .replace(/\n{3,}/g, '\n\n')
      .trim();

    const lines = textContent.split('\n\n');

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;

      // Check for table-like content (pipe-delimited)
      if (trimmed.includes('|') && trimmed.includes('\n')) {
        elements.push(...this.parseTable(trimmed));
        continue;
      }

      // Determine if it's a heading
      if (trimmed.length < 100 && !trimmed.endsWith('.') && !trimmed.endsWith(':')) {
        elements.push(
          new Paragraph({
            children: [
              new TextRun({
                text: trimmed,
                bold: true,
                size: 28, // 14pt
                font: 'Calibri',
              }),
            ],
            spacing: { after: 200, before: 200 },
          })
        );
      } else {
        elements.push(
          new Paragraph({
            children: [
              new TextRun({
                text: trimmed,
                size: 22, // 11pt
                font: 'Calibri',
              }),
            ],
            spacing: { after: 120 },
          })
        );
      }
    }

    return elements;
  }

  /**
   * Parse pipe-delimited table content
   */
  private static parseTable(text: string): Table[] {
    const rows = text.trim().split('\n');
    const tableRows: TableRow[] = [];

    for (let i = 0; i < rows.length; i++) {
      const cells = rows[i].split('|').filter(c => c.trim());
      // Skip separator rows (e.g., |---|---|)
      if (cells.every(c => c.trim().match(/^-+$/))) continue;

      tableRows.push(
        new TableRow({
          children: cells.map(
            (cell) =>
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: cell.trim(),
                        bold: i === 0, // First row as header
                        size: 22,
                      }),
                    ],
                  }),
                ],
              })
          ),
        })
      );
    }

    if (tableRows.length > 0) {
      return [
        new Table({
          rows: tableRows,
        }),
      ];
    }

    return [];
  }
}
