import type { ExportOptions } from '@/types';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  AlignmentType,
  ImageRun,
  PageBreak,
} from 'docx';

/**
 * DocMint DOCX Generator
 * Generates Microsoft Word (.docx) documents using the docx library.
 * Supports images from data URIs and proper HTML-to-DOCX conversion.
 */
export class DOCXGenerator {
  /**
   * Generate a DOCX file from HTML content
   */
  static async generate(
    htmlContent: string,
    options: Partial<ExportOptions> & { title?: string } = {}
  ): Promise<Buffer> {
    try {
      // Parse HTML content into docx elements
      const children = await this.parseHtmlToDocxElements(htmlContent);

      // Create the document
      const doc = new Document({
        title: options.title || 'Document',
        creator: 'DocMint',
        description: 'Generated by DocMint',
        styles: {
          default: {
            document: {
              run: {
                size: 22, // 11pt
                font: 'Calibri',
              },
            },
          },
        },
        sections: [
          {
            properties: {
              page: {
                margin: {
                  top: 1440, // 1 inch in twips
                  right: 1440,
                  bottom: 1440,
                  left: 1440,
                },
              },
            },
            children,
          },
        ],
      });

      // Generate buffer
      const buffer = await Packer.toBuffer(doc);
      return Buffer.from(buffer);
    } catch (error) {
      console.error('DOCX generation error:', error);
      throw new Error('Failed to generate DOCX document');
    }
  }

  /**
   * Generate a preview (returns HTML representation)
   */
  static async generatePreview(htmlContent: string): Promise<string> {
    return htmlContent;
  }

  /**
   * Decode a base64 data URI into a Buffer and extract MIME type + dimensions
   */
  private static decodeDataUri(uri: string): { buffer: Buffer; mimeType: string } | null {
    try {
      const match = uri.match(/^data:([^;]+);base64,(.+)$/);
      if (!match) return null;
      const mimeType = match[1];
      const base64 = match[2];
      const buffer = Buffer.from(base64, 'base64');
      if (buffer.length === 0) return null;
      return { buffer, mimeType };
    } catch {
      return null;
    }
  }

  /**
   * Estimate image dimensions based on content type and constraints
   */
  private static estimateImageDimensions(
    buffer: Buffer,
    maxWidthEmu: number = 5000000 // ~5 inches in EMU
  ): { width: number; height: number } {
    // For simplicity, use square-ish aspect ratio since we can't parse image headers here
    // DOCX uses EMU (English Metric Units): 1 inch = 914400 EMU
    // Default to a reasonable size
    const aspectRatio = 1.4; // Assume roughly 1.4:1 width:height ratio
    const width = Math.min(maxWidthEmu, 4000000); // ~4.37 inches
    const height = Math.round(width / aspectRatio);
    return { width, height };
  }

  /**
   * Parse HTML content into docx elements, preserving images
   */
  private static async parseHtmlToDocxElements(html: string): Promise<(Paragraph | Table)[]> {
    const elements: (Paragraph | Table)[] = [];

    // Helper to process inline content (text + images)
    const processInlineContent = async (text: string, defaultBold: boolean = false, defaultSize: number = 22): Promise<(Paragraph | Table)[]> => {
      const elements: (Paragraph | Table)[] = [];
      const parts: { type: 'text' | 'image'; content: string; bold?: boolean; size?: number }[] = [];

      // Extract images first
      const imgRegex = /<img[^>]+src="([^"]*)"[^>]*\/?>/gi;
      let imgMatch;
      let textCursor = 0;

      while ((imgMatch = imgRegex.exec(text)) !== null) {
        // Add text before this image
        const beforeText = text.substring(textCursor, imgMatch.index);
        if (beforeText.trim()) {
          parts.push({ type: 'text', content: beforeText, bold: defaultBold, size: defaultSize });
        }

        // Add image
        parts.push({ type: 'image', content: imgMatch[1] });
        textCursor = imgMatch.index + imgMatch[0].length;
      }

      // Add remaining text
      const afterText = text.substring(textCursor);
      if (afterText.trim()) {
        parts.push({ type: 'text', content: afterText, bold: defaultBold, size: defaultSize });
      }

      if (parts.length === 0) return [];

      // Group consecutive text parts into one paragraph
      const currentRuns: (TextRun | ImageRun)[] = [];
      let textAccumulator = '';

      const flushText = () => {
        if (textAccumulator.trim()) {
          currentRuns.push(
            new TextRun({
              text: textAccumulator.trim(),
              bold: defaultBold,
              size: defaultSize,
              font: 'Calibri',
            })
          );
          textAccumulator = '';
        }
      };

      for (const part of parts) {
        if (part.type === 'text') {
          textAccumulator += part.content + ' ';
        } else if (part.type === 'image') {
          flushText();
          const decoded = this.decodeDataUri(part.content);
          if (decoded) {
            const dims = this.estimateImageDimensions(decoded.buffer);
            currentRuns.push(
              new ImageRun({
                type: decoded.mimeType.includes('png') ? 'png' : 'jpg',
                data: decoded.buffer,
                transformation: {
                  width: dims.width,
                  height: dims.height,
                },
              })
            );
          }
        }
      }

      flushText();

      if (currentRuns.length > 0) {
        elements.push(
          new Paragraph({
            children: currentRuns,
            spacing: { after: 120 },
          })
        );
      }

      return elements;
    };

    // Process the HTML block by block
    // First, wrap the entire HTML in a container for processing
    const container = `<docroot>${html}</docroot>`;

    // Simple state-machine parser
    let i = 0;
    let currentText = '';

    const flushText = async () => {
      if (currentText.trim()) {
        const inlineElements = await processInlineContent(currentText);
        elements.push(...inlineElements);
        currentText = '';
      }
    };

    while (i < container.length) {
      if (container[i] === '<') {
        const closeBracket = container.indexOf('>', i);
        if (closeBracket === -1) break;

        const tag = container.substring(i, closeBracket + 1);
        const tagLower = tag.toLowerCase();

        // Handle block-level tags
        if (tagLower.startsWith('<p') || tagLower.startsWith('</p') ||
            tagLower.startsWith('<h1') || tagLower.startsWith('</h1') ||
            tagLower.startsWith('<h2') || tagLower.startsWith('</h2') ||
            tagLower.startsWith('<h3') || tagLower.startsWith('</h3') ||
            tagLower.startsWith('<h4') || tagLower.startsWith('</h4') ||
            tagLower.startsWith('<h5') || tagLower.startsWith('</h5') ||
            tagLower.startsWith('<h6') || tagLower.startsWith('</h6') ||
            tagLower.startsWith('<br') || tagLower.startsWith('<li') || tagLower.startsWith('</li')) {
          await flushText();
        }
        // Handle the editor's page-break marker div (.doc-page-break) — emit a
        // real Word page break so exported DOCX honors the editor's A4 pages.
        else if (tagLower.startsWith('<div') && tagLower.includes('doc-page-break')) {
          await flushText();
          elements.push(
            new Paragraph({
              children: [new PageBreak()],
              spacing: { after: 0, before: 0 },
            })
          );
        }
        // Handle generic divs as block boundaries (content preserved)
        else if (tagLower.startsWith('<div') || tagLower.startsWith('</div')) {
          await flushText();
        }
        // Handle images
        else if (tagLower.startsWith('<img')) {
          const srcMatch = tag.match(/src="([^"]*)"/);
          if (srcMatch && srcMatch[1]) {
            await flushText();
            const decoded = this.decodeDataUri(srcMatch[1]);
            if (decoded) {
              const dims = this.estimateImageDimensions(decoded.buffer);
              elements.push(
                new Paragraph({
                  children: [
                    new ImageRun({
                      type: decoded.mimeType.includes('png') ? 'png' : 'jpg',
                      data: decoded.buffer,
                      transformation: {
                        width: dims.width,
                        height: dims.height,
                      },
                    }),
                  ],
                  spacing: { after: 120 },
                  alignment: AlignmentType.CENTER,
                })
              );
            }
          }
        } else if (tagLower.startsWith('</docroot')) {
          await flushText();
        } else if (tagLower.startsWith('<style') || tagLower.startsWith('</style') ||
                   tagLower.startsWith('<script') || tagLower.startsWith('</script') ||
                   tagLower.startsWith('<meta') || tagLower.startsWith('<head') || tagLower.startsWith('</head') ||
                   tagLower.startsWith('<html') || tagLower.startsWith('</html') ||
                   tagLower.startsWith('<body') || tagLower.startsWith('</body') ||
                   tagLower.startsWith('<!')) {
          // Skip these tags
        } else if (tagLower.startsWith('<strong') || tagLower.startsWith('</strong') ||
                   tagLower.startsWith('<b') || tagLower.startsWith('</b') ||
                   tagLower.startsWith('<em') || tagLower.startsWith('</em') ||
                   tagLower.startsWith('<i') || tagLower.startsWith('</i') ||
                   tagLower.startsWith('<u') || tagLower.startsWith('</u') ||
                   tagLower.startsWith('<span') || tagLower.startsWith('</span') ||
                   tagLower.startsWith('<a') || tagLower.startsWith('</a')) {
          // Preserve content inside these tags
          // Just consume the tag
        } else {
          // Unknown tag - just consume it
        }

        i = closeBracket + 1;
      } else {
        currentText += container[i];
        i++;
      }
    }

    // If no elements were produced, fall back to simple text extraction
    if (elements.length === 0) {
      const textContent = html
        .replace(/<br\s*\/?>/gi, '\n')
        .replace(/<\/p>/gi, '\n')
        .replace(/<\/h[1-6]>/gi, '\n')
        .replace(/<\/div>/gi, '\n')
        .replace(/<[^>]*>/g, '')
        .replace(/\n{3,}/g, '\n\n')
        .trim();

      const lines = textContent.split('\n\n');

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) continue;

        // Check for table-like content (pipe-delimited)
        if (trimmed.includes('|') && trimmed.includes('\n')) {
          elements.push(...this.parseTable(trimmed));
          continue;
        }

        // Determine if it's a heading
        if (trimmed.length < 100 && !trimmed.endsWith('.') && !trimmed.endsWith(':')) {
          elements.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: trimmed,
                  bold: true,
                  size: 28,
                  font: 'Calibri',
                }),
              ],
              spacing: { after: 200, before: 200 },
            })
          );
        } else {
          elements.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: trimmed,
                  size: 22,
                  font: 'Calibri',
                }),
              ],
              spacing: { after: 120 },
            })
          );
        }
      }
    }

    return elements;
  }

  /**
   * Parse pipe-delimited table content
   */
  private static parseTable(text: string): Table[] {
    const rows = text.trim().split('\n');
    const tableRows: TableRow[] = [];

    for (let i = 0; i < rows.length; i++) {
      const cells = rows[i].split('|').filter(c => c.trim());
      // Skip separator rows
      if (cells.every(c => c.trim().match(/^-+$/))) continue;

      tableRows.push(
        new TableRow({
          children: cells.map(
            (cell) =>
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: cell.trim(),
                        bold: i === 0,
                        size: 22,
                      }),
                    ],
                  }),
                ],
              })
          ),
        })
      );
    }

    if (tableRows.length > 0) {
      return [
        new Table({
          rows: tableRows,
        }),
      ];
    }

    return [];
  }
}
